# Generated by Django 5.1.4 on 2025-01-12 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyuser",
            name="position",
            field=models.CharField(
                choices=[(1, "employee"), (2, "manager")], default=1, max_length=1
            ),
        ),
        migrations.CreateModel(
            name="Leaves",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_of_days", models.IntegerField(default=0, max_length=12)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[(1, "casual"), (2, "sick")], default=1, max_length=1
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[(1, "casual"), (2, "sick")], default=1, max_length=1
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
