# Generated by Django 5.1.4 on 2025-01-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_leaves_no_of_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyuser",
            name="position",
            field=models.IntegerField(
                choices=[(1, "employee"), (2, "manager")], default=1, max_length=1
            ),
        ),
    ]
