# Generated by Django 5.1.4 on 2025-01-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_companyuser_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyuser",
            name="position",
            field=models.CharField(
                choices=[("employee", "employee"), ("manager", "manager")],
                default=1,
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="leaves",
            name="leave_type",
            field=models.CharField(
                choices=[("casual", "casual"), ("sick", "sick")],
                default=1,
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="leaves",
            name="status",
            field=models.CharField(
                choices=[("casual", "casual"), ("sick", "sick")],
                default=1,
                max_length=100,
            ),
        ),
    ]
